### ISSUE TITLE
同一个css文件，有的有?sprite，有的没有，结果会打成一个文件

### ISSUE THREAD

**Issue by z-ZYS-s** [vusion/svg-classic-sprite-loader#3]
``` css
.root {
    width: 50px;
    height: 50px;
    background: url('./assets/twitter.svg');
}
.svg {
    width: 50px;
    height: 50px;
    background: url('./assets/react.svg?sprite');
}
```

结果打出来只有一个文件`sprite.8b1043c7e9dd0844.svg`，参见https://github.com/vusion/vusion-cli/blob/develop/test/fixtures/svg-sprite/index.html
